### PR TITLE
Updated installation options

### PR DESCRIPTION
**Pull request by marumari**
Two new ways to run your local badssl:

- Run "make install", which will do everything to your local machine besides fiddling with nginx.conf
- Run via docker, where you can get a fully running and configured Docker image in two easy commands

### CODE REVIEW

**Comment by lgarron** [comment]
I can't get Docker to work from inside a VMWare Linux VM:

I ran into 

    debconf: unable to initialize frontend: Dialog
    debconf: (TERM is not set, so the dialog frontend is not usable.)
    debconf: falling back to frontend: Readline
    debconf: unable to initialize frontend: Readline
    debconf: (This frontend requires a controlling tty.)
    debconf: falling back to frontend: Teletype

Based on [this link](https://serverfault.com/questions/618994/when-building-from-dockerfile-debian-ubuntu-package-install-debconf-noninteract), the solution was to add a line:

    ENV DEBIAN_FRONTEND noninteractive

However, I still get:

     Removing any system startup links for /etc/init.d/rsync ...
    update-rc.d: warning: default stop runlevel arguments (0 1 6) do not match rsync Default-Stop values (none)
     Adding system startup for /etc/init.d/rsync ...
       /etc/rc0.d/K20rsync -> ../init.d/rsync
       /etc/rc1.d/K20rsync -> ../init.d/rsync
       /etc/rc6.d/K20rsync -> ../init.d/rsync
       /etc/rc2.d/S20rsync -> ../init.d/rsync
       /etc/rc3.d/S20rsync -> ../init.d/rsync
       /etc/rc4.d/S20rsync -> ../init.d/rsync
       /etc/rc5.d/S20rsync -> ../init.d/rsync
    invoke-rc.d: policy-rc.d denied execution of restart.
    Setting up xauth (1:1.0.7-1ubuntu1) ...
    Setting up xml-core (0.13+nmu2) ...
    Setting up liberror-perl (0.17-1.1) ...
    Setting up git-man (1:1.9.1-1ubuntu0.1) ...
    Setting up git (1:1.9.1-1ubuntu0.1) ...
    Setting up make (3.81-8.2ubuntu3) ...
    Setting up nginx-common (1.4.6-1ubuntu3.2) ...
    Setting up patch (2.7.1-4ubuntu2) ...
    Processing triggers for ureadahead (0.100.0-16) ...
    Setting up nginx-core (1.4.6-1ubuntu3.2) ...
    invoke-rc.d: policy-rc.d denied execution of start.
    Setting up nginx (1.4.6-1ubuntu3.2) ...
    Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
    Processing triggers for ca-certificates (20141019ubuntu0.14.04.1) ...
    Updating certificates in /etc/ssl/certs... 173 added, 0 removed; done.
    Running hooks in /etc/ca-certificates/update.d....done.
    Processing triggers for sgml-base (1.26+nmu4ubuntu1) ...
     ---> 14a46cde2176
    Removing intermediate container 2640c87f09d5
    Step 5 : RUN git clone https://github.com/marumari/badssl.com.git
     ---> Running in 2e5a104b1709
    Cloning into 'badssl.com'...
     ---> 85f846612cac
    Removing intermediate container 2e5a104b1709
    Step 6 : RUN cd badssl.com ; make install
     ---> Running in 744d4fecb2b3
    make: *** No rule to make target `install'.  Stop.
    INFO[0044] The command [/bin/sh -c cd badssl.com ; make install] returned a non-zero code: 2

**Comment by marumari** [comment]
Oh!  

1) it should use your repository instead of mine
2) it's wouldn't work unless I merged my "install" branch into master; this is done, so everything should work nicely

After accepting the pull request, make sure to change where it pulls from it git  :)

**Comment by marumari** [comment]
Looks like we can probably close this one, since it was merged in already?  Everything working okay with those docker images?

**Comment by lgarron** [comment]
I got the image to work, but haven't been able to test it properly yet; any quick instructions on what to do (visit pages, install certs, tinker with `/etc/hosts`)?

**Comment by marumari** [comment]
Steps:

Build docker image:
docker build -t badssl .

Start docker image:
docker run -d -p 80:80 -p 443:443 --name badssl badssl

Setup your host file to point to all the right sites:
192.168.1.2 badssl.com www.badssl.com expired.badssl.com wrong.host.badssl.com self-signed.badssl.com incomplete-chain.badssl.com sha1.badssl.com mixed.badssl.com rc4.badssl.com cbc.badssl.com hsts.badssl.com preloaded-hsts.badssl.com sha1-2016.badssl.com sha1-2017.badssl.com broken-diffie-hellman.badssl.com weak-diffie-hellman.badssl.com rsa512.badssl.com rsa1024.badssl.com sha256.badssl.com dh480.badssl.com dh512.badssl.com dh1024.badssl.com dh2048.badssl.com http.badssl.com dh-small-subgroup.com dh-composite.badssl.com

Grab and install the root certificate (you can grab it via docker exec or whatever); this is why I recommend making it accessible to the http site:
http://http.badssl.com/certs/badssl-root.pem

Visit the site and have fun!

**Comment by marumari** [comment]
How's it going on testing this?  :)

**Comment by lgarron** [comment]
> How's it going on testing this? :)

I didn't get it to work the firs try, then I was busy and gone. :-P
I'll try to get verify everything and merge this week.

**Comment by marumari** [comment]
Woohoo!  I hear you on being super busy!  *flails*

**Comment by lgarron** [comment]
Urgh, I didn't have time, and I'll be cubing until Monday. Soon, I promise! :-D

**Comment by marumari** [comment]
Hah, it's no biggie.  Life has been crazy for me at Mozilla as well, hence my lack of recent contributions.  O_o

**Comment by lgarron** [comment]
`make install` should now make `http://http.badssl.com/certs/badssl-root.pem` available.

**Comment by marumari** [comment]
Success!  I win!  :D

**Pull request closed without merging**
