### PR TITLE
Adding 1000-sans and 10000-sans, fixing minor cert-generator bug

### PR DESCRIPTION
**Pull request by marumari**
An obvious attempt to up my github lines-of-code count.

### CODE REVIEW

**Comment by Hoverbear** [comment]
I picture you saying to yourself this morning:

> Today, I will be dark green on Github.

**Comment by marumari** [comment]
Mostly I'm just daydreaming about pulling ahead of @lgarron in the Contributor Race.  :D

**Comment by lgarron** [comment]
> An obvious attempt to up my github lines-of-code count.

I dare say someone's feeling too lazy to generate SANs programatically! :-P

Do these crash Chrome, et al. even if the cert is invalid? If so, I'd like to find a way to serve it from badssl.com
(Extra credit: convince a CA to sign this for us.)

**Comment by marumari** [comment]
I mean, I generated the list of SANs with a program, so I'm obviously not that lazy!  I just didn't want to deal with the hassle of creating temporary files, removing them, having git ignore them, etc.

On the 10000-sans page, Chrome will spit up this error:

SSL error

So it doesn't really matter if it's valid in that sense, to see Chrome rejecting things.  The 1000-san one does work, and would obviously generate an error with Chrome, being self-signed and all.

Your CA _should_ sign these: there's nothing in the RFC that specifies an upper bound to the number of SANs that a certificate can contain.

**Comment by lgarron** [comment]
> I just didn't want to deal with the hassle of creating temporary files, removing them, having git ignore them, etc.

Process substitution?

I don't mind the current approach, but it would be nice if it were trivial to generate certs with 1023 or 100,000 SANs using the same code.

**Comment by marumari** [comment]
I'll be happy to put in the effort should be there be enough demand for it.  I just don't think it's worth it at the moment, is it?

```
#!/usr/bin/env python

import sys

if len(sys.argv) != 2:
    print sys.argv[0] + ' <number of sans>'
    sys.exit(1)

print 'DNS.1 = ' + str(sys.argv[1]) + '-sans.badssl.com'

for i in range(2, int(sys.argv[1]) + 1):
    print 'DNS.' + str(i) + ' = wowmoarhost' + str(i) + '.badssl.com'
```

**Comment by lgarron** [comment]
> I just don't think it's worth it at the moment, is it?

I'd prefer it, but I guess there's some value in having the cert sources hard-coded so that they're straightforward to look at.

**Comment by Hoverbear** [comment]
@lgarron I could try to get Let's Encrypt to sign it, I have a beta invite for my hoverbear.org domain. :)

**Comment by marumari** [comment]
@lgarron, any chance we could merge this PR?  I've got another site to work on that will also require changes to the certificate generator, and I'd like to let you avoid the hassle of merging resolution.  :)

**Comment by lgarron** [comment]
> @lgarron, any chance we could merge this PR? I've got another site to work on that will also require changes to the certificate generator, and I'd like to let you avoid the hassle of merging resolution. :)

Hey, hey, give this millennial a good night's sleep and let them roll out of bed before poking. :-P
(Will look at outstanding PRs now.)

**Comment by marumari** [comment]
:point_right: :sleeping:
:point_right: :sleeping:
:point_right: :sleeping:
:point_right: :sleeping:
:point_right: :sleeping:

**Pull request merged**
