### PR TITLE
Add http password site

### PR DESCRIPTION
**Pull request by marumari**
Should be visible at: http://http.badssl.com/password/

Screenshot: http://i.imgur.com/PGUrh1W.png

As per this upcoming Firefox change: https://twitter.com/rlbarnes/status/656554266744586240

P.S.: The public site has been very very slow lately

P.P.S.: Styling placeholder text is the literal worst

### CODE REVIEW

**Comment by lgarron** [comment]
Will http://http.badssl.com/mixed/password-form/ do? (Made it an hour ago, but haven't pushed it.)

**Comment by marumari** [comment]
They are doing different things.

mixed/password -> https site that submits to an http form
http/password -> http site with a password field

They trigger different conditions: the first triggers a warning popup in Firefox and the latter will trigger an insecure icon starting in FF44.  As such, they should probably both exist.

Also feel free to steal my totally prettier CSS.  :)

**Comment by marumari** [comment]
They are doing different things.

mixed/password -> https site that submits to an http form
http/password -> http site with a password field

They trigger different conditions: the first triggers a warning popup in Firefox and the latter will trigger an insecure icon starting in FF44.  As such, they should probably both exist.

Also feel free to steal my totally prettier CSS.  :)

**Comment by lgarron** [comment]
> P.S.: The public site has been very very slow lately

I'm not seeing much latency. Any particular pages/times?

**Comment by marumari** [comment]
Err, never mind the slowness issue.  I had been connecting via the Mozilla VPN, and I just read the email saying that the VPN was having troubles.  >_<

**Comment by marumari** [comment]
FYI, the main page currently has a link for it, but I get a 404 error.

**Comment by lgarron** [comment]
> FYI, the main page currently has a link for it, but I get a 404 error.

Yeah, I don't know what's going wrong. Taking a look at it again. :-(

**Comment by lgarron** [comment]
I had a bad local merge for pushing. Sorry for the multiple-day delay. :-(

Also, I hope you don't mind that I aligned the styling with mixed/password.

**Comment by marumari** [comment]
But my style was amazing!  All that time styling the shadow DOM.  :(

**Comment by lgarron** [comment]
> But my style was amazing! All that time styling the shadow DOM. :(

It was amazing! But I was very bothered by the centered cursor. :-(

Also, styling shadow DOM is a recipe for un-fun. :-(

**Comment by marumari** [comment]
The cursor was meant to be there so that you knew that if you typed that 
you would get those sweet giant password asterisks.  :)

**Comment by lgarron** [comment]
> The cursor was meant to be there so that you knew that if you typed that
> you would get those sweet giant password asterisks.  :)

Yeah, I liked that idea!
It made me realize that showing the dots would actually be the clearest way to do this.

(The rest is a benevolent stroke of leade^W^W^W^W^Whistory. u forgivz me?)

**Comment by lgarron** [comment]
I really want to tackle #46 and #59 some time soon, though. Then maybe my consistent styling arguments will hold water. :-P

**Comment by lgarron** [comment]
How would you feel about moving this to `http-password.badssl.com`?

Apart from the `mixed/*` pages, everything else linked from the front page is its own domain.
(I think there's value in making the `mixed/*` pages available on every domain to test the compounded effect of mixed content, but I'm also wondering if each of those should have a separate, canonical `mixed-*.badssl.com` domain for testing in isolation.)

**Comment by marumari** [comment]
Sure, that's fine.  :)

**Comment by lgarron** [comment]
Alright, I promise I'm done tinkering for the day.

screen shot 2015-10-22 at 19 17 53

**Comment by marumari** [comment]
Ooo, that looks pretty nice.  But I'll still daydream about frolicking through fields of daisies and typing in giant •••••••••s.  :)

**Comment by marumari** [comment]
BTW, I see the new site, but the front page still links to my awesome version.  :)

**Pull request merged**
