### PR TITLE
Docker + Makefile + New Homepage + Cleanup

### PR DESCRIPTION
**Pull request by marumari**
Okay, this pull request should remove every pem/key file in badssl.com, except for the two weak DH ones.  Every other one should be generated via running make keys (or by invoking the certificate generator directly).

The Dockerfile successfully builds to a full and functional instance of badssl.com, provided you grab the cert file from http://http.badssl.com/badssl-root.pem.

### CODE REVIEW

**Comment by lgarron** [comment]
Any chance you could split up your pull request? It would make it a lot easier (=> faster) for me to evaluate and merge individual changes.

In this case, I'd like to avoid merging the changes to the home page, because I want it to be simple by default. (If we're going to remove the "More" button, I think the list should be made more dense, and the backgrounds replaced with more concise iconography. But that's a separate discussion.)

The other stuff sounds good, but separate pull requests would still help me understand them better. :-)

**Comment by marumari** [comment]
I don't know if github will actually let me do it at this point.  Any clue on how to do so?

I actually think the new homepage looks pretty decent, and not really that complicated:

http://www.twoevils.org/files/tmp/badssl/

Who is the user that we are targeting for the "simple" page?  Are people besides TLS client implementers using it?  I honestly find the current page to be pretty confusing, both in order and lack of categorization, and I've clicked that More... button about a zillion times by now and it's making me crazy.  :P

**Comment by lgarron** [comment]
I actually like the organization from this PR, but the existing styles make it look very ugly (I know, I know, I wrote them...).

Splitting the CL should be easy if you're comfortable with git branches (and cherry-picking/rebasing).
I tend to be a bit pedantic about a clean history, so when I see a bunch of unrelated changes interleaved in a handful of commits I always pause. Any chance you could split this into different CLs, or at least isolated commits per change? (e.g. 7d5eab6745db02615e1d8892ca871fd7df1c057f shouldn't include installation code, especially if not included in the commit message)

If not, I'll probably do some heavy rebasing and merge this weekend.

**Comment by marumari** [comment]
I’m not super comfortable with them, but there’s no time like the present to learn.  I’ll take a look this weekend, and see if I can split things up into a bunch of different branches.  :)

**Comment by lgarron** [comment]
Thanks for splitting these; sorry I haven't had time to merge them yet; should be quick when I find enough time.

**Comment by marumari** [comment]
Anything for you!  ;)

**Pull request closed without merging**
