### PR TITLE
Utilize datafile

### PR DESCRIPTION
**Pull request by Hoverbear**
As mentioned to in #46 we can use Jekyll's `data/` directory to build out some common data. I'd like to harness this to make adding and altering domains and certs much easier.

This PR is not meant to change the end-result of BadSSL, but instead be used as a launching point for #46, #103, #102, and #86.

Changes:

* `_data/*.yml` files that contain cross-site data.
* `**/badssl.com/index.html` refined to include both animated JS-less descriptions and pull data from the data files.

I'd appreciate feedback and suggestions earlier rather than later. :)

### CODE REVIEW

**Comment by Hoverbear** [comment]
I moved `certs/*/*.conf` into `certs/**/*.conf` which dramatically cleans up the folder layout and will make it easier in the future to maintain. Waiting #129 before I can test it.

**Comment by Hoverbear** [comment]
@marumari I think this is ready for a second set of eyes if you'd be willing to test this out and give some feedback. Do you think anything else would be appropriate to contain in the datafile?

**Comment by Hoverbear** [comment]
Currently there are some bugs with `hsts` and the upgrade domains, I'm working on figuring those out.

**Comment by Hoverbear** [comment]
Got it! \o/

**Comment by marumari** [comment]
Since this is blocking you, I'm going to trust that you've got it working.  I'll just file bugs down the road if my builds fail.  :)

**Comment by Hoverbear** [comment]
(There was a miscommunication here, merge accidental)

**Pull request merged**
