### PR TITLE
Add an example of active mixed content

### PR DESCRIPTION
**Pull request by bifurcation**
Browsers have different behavior for active vs. passive mixed content.  The current badssl.com only has an example of passive mixed content.  This PR adds an example page for active mixed content.  It's yellow on the main page, because most browsers block it.  The page contains a reference to non-secure JS.  It displays as yellow if JS is blocked, but if the JS is loaded, it turns the page red and displays a message.

### CODE REVIEW

**Comment by marumari** [comment]
Maybe I'm missing something, but I'm not certain why this would generate a mixed content warning.  The page is delivered over https, retrieves a resource of './nonsecure.js' (which shouldn't need the path), and there's no redirection back to the http site on mixed-active.badssl.com.

**Comment by marumari** [comment]
@lgarron: What do you think about moving nonsecure.js to:

http://http.badssl.com/scripts/mixed-active.js to make it a bit more explicit what is happening?

Otherwise, I'm down with the PR if you are.

**Comment by bifurcation** [comment]
@marumari, that seems like a good idea, so I went ahead and implemented it for both this and the static mixed content example.

**Comment by lgarron** [comment]
Hmm, I've been using very.badssl.com for that.

A separate domain might be easy to remember, but "mixed-active" doesn't sound right to my ear. How about just straight-up `mixed-script`?

I've also been meaning to add various types of mixed content on the each domain (but still linked from the front page. This would go at <https://*.badssl.com/mixed-content/script>.

**Comment by marumari** [comment]
Moving it to very.badssl.com seems equally as reasonable as http.badssl.com.  mixed-active sounds a bit better to my ear, but I don't think it's actually technically defined anywhere, so either name is good.

That said, I don't know what adding mixed content to every domain will accomplish?  Do any agents treat mixed content with, say, RC4 differently than they do with SHA1 certs or the like?

**Comment by lgarron** [comment]
> Moving it to very.badssl.com seems equally as reasonable as http.badssl.com. mixed-active sounds a bit better to my ear, but I don't think it's actually technically defined anywhere, so either name is good.

I meant to say `very.badssl.com` already has active mixed content, so I've been using it as my active mixed content test site already.

As for where to host the HTTP content, I'm still not sure whether I prefer them all at `http.badssl.com` or on a sub-folder common to each domain (that doesn't redirect from HTTP to HTTPS, and maybe even redirects HTTPS to HTTP).

> That said, I don't know what adding mixed content to every domain will accomplish? Do any agents treat mixed content with, say, RC4 differently than they do with SHA1 certs or the like?

I'll be using combinations like this a lot, for testing our new Security panel. ;-)

**Comment by lgarron** [comment]
Anyhow, @bifurcation, if you're could modify this PR use `mixed-script.badssl.com` and follow the `mixed.badssl.com` setup, I'd be out of stuff to nitpick, and would be happy to merge this now. :-P

**Comment by marumari** [comment]
New security panels?  Man, you Googlers get all the cool toys!

**Comment by marumari** [comment]
> As for where to host the HTTP content, I'm still not sure whether I prefer them all at http.badssl.com or on a sub-folder common to each domain (that doesn't redirect from HTTP to HTTPS, and maybe even redirects HTTPS to HTTP).

I think http.badssl.com makes things much clearer, personally.  It also keeps the individual configuration files a lot cleaner.

**Comment by bifurcation** [comment]
@marumari Argh.  I just reversed that.

@lgarron Moved to `mixed-script`

Can we all live with this state?

**Comment by marumari** [comment]
@bifurcation I know, I'll keep beating up on @lgarron until I get my way someday.  :)

Looks fine to me.  @lgarron, can we merge?

**Pull request merged**
